//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDiploma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomMenuMeals
    {
        public int Id { get; set; }
        public int CustomMenuId { get; set; }
        public int DishId { get; set; }
    
        public virtual CustomMenu CustomMenu { get; set; }
        public virtual Dish Dish { get; set; }
    }
}
