//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDiploma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ord()
        {
            this.Meals = new HashSet<Meals>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int WaiterId { get; set; }
        public System.DateTime TimeOpen { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public int TableId { get; set; }
        public double TotalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meals> Meals { get; set; }
        public virtual RegUser RegUser { get; set; }
        public virtual Tabl Tabl { get; set; }
        public virtual RegUser RegUser1 { get; set; }
    }
}
