//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDiploma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CustomMenu> CustomMenu { get; set; }
        public virtual DbSet<CustomMenuMeals> CustomMenuMeals { get; set; }
        public virtual DbSet<Dish> Dish { get; set; }
        public virtual DbSet<DishEntry> DishEntry { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Ord> Ord { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<RegUser> RegUser { get; set; }
        public virtual DbSet<RegUserRole> RegUserRole { get; set; }
        public virtual DbSet<Tabl> Tabl { get; set; }
    }
}
